def quiz_base():
    # THE FIRST ONE IS ALWAYS CORRECT

    return {
        'Wann hat LH seinen YouTube-Kanal gegründet?': ['2016', '2014', '2018', '2020'],
        'Wie viele Videos hat LH (Stand August 2021)?': ['170', '50', '120', '240'],
        'Was ist LH\'s erstes YouTube-Video?': ['Hacken Lernen', 'Boss of Technic - Channel Intro', 'Kali Linux Tutorial', 'VPN Tutorial'],
        'Was hilft der Privatsphäre am meisten?': ['Tor', 'eine VPN', 'Proxy', 'Firefox'],
        'Was davon ist das sicherste Betriebssystem?': ['Tails', 'Kali Linux', 'Windows', 'MacOS'],
        'Welche Programmiersprache ist die häufigste auf GitHub?': ['JavaScript', 'Python', 'C', 'C++'],
        'Welche von diesen Extensions hilft der Privatsphäre am meisten?': ['uBlock Origin', 'AdBlockPlus', 'DarkReader', 'Tails'],
        'Was ist die IP Adresse für localhost?': ['127.0.0.1', '255.255.255.0', '111.111.111.1', '1.1.1.1'],
        'Welchen von diesen Kanälen hat LH auf YouTube abonniert?': ['LinusTechTips', 'The Morpheus Tutorials', 'NeuralNine', 'WhatAboutCoding'],
        'Welche sichere Suchmaschine ist am beliebtesten?': ['DuckDuckGo', 'Google', 'Qwant', 'Startpage'],
        'Welche von diesen Unternehmen sammelt die meisten Daten?': ['Google', 'Microsoft', 'Apple', 'Amazon'],
        'Was ist LH\'s meistgeklicktes Video (Stand August 2021)?': ['Jedes Handy hacken', 'Hacker werden', 'Kali Linux Sprache ändern', 'Batch Script Tutorial'],
        'Was ist LH\'s Internetseite?': ['huber-luis.de', 'boss-of-technic.de', 'lh-cybersecurity.de', 'cybersecurity.net'],
        'Wann hat LH sein Instagram-Konto erstellt?': ['2020', '2018', '2016', '2015'],
        'Wie viele Mitglieder hat der Discord Server (Stand August 2021)?': ['300', '100', '1200', '600'],
        'Was ist die Malware, die am meisten Geld aller Zeiten gewesen?': ['MyDoom', 'WannaCry', 'Locky', 'Conf*cker'],
        'In welchem Jahr ist WannaCry ausgebrochen?': ['2017', '2014', '2012', '2019'],
        'Auf welcher Schwachstelle basiert WanaCry?': ['EternalBlue', 'MyDoom', 'CrytoMiner', 'xLock'],
        'Was ist Social Engineering?': ['Die Schwachstelle ist der Mensch', 'Soziale Netzwerk-Unternehmen, z.B. Facebook', 'Das Programmieren von sozialen Medien', 'Partnerunternehmen'],
        'Was ist eine IDE?': ['ein Texteditor, der für Code spezialisiert ist', 'InternalDataExploit = schwerwiegende Sicherheitslücke', 'ein Übertragungsprotokoll', 'ein Hardwareproblem'],
        'Was ist stackoverflow.com?': ['ein Soziales Netzwerk für Programmierer', 'ein online-Tool zum Hacken', 'eine Webseite zum Ausführen von Code', 'eine PC-Marke'],
        'Was davon ist ein Hex-Code?': ['#123ABC', 'FFFFFG', '256, 128, 64', 'x7H1GhK8Hw=='],
        'Was davon ist die Farbe rot als Hex-Code?': ['FF0000', 'RD0000', 'RR0000', '00FF00'],
        'Was ist RegEx?': ['ein Tool, das Text validiert', 'RegularExploit = Schwachstellen bei Standardkonfigurationen', 'eine Webseite für Hacking-Tools', 'ein Mainboard-Anschluss'],
        'Was ist davon hat nichts mit Git(Hub) zu tun?': ['Cursor', 'Branch', 'Pull', 'Fork'],
        'Was hat nichts mit Hardware zu tun?': ['CDU', 'CPU', 'GPU', 'PSU'],
        'Was ist HashCat?': ['ein Tool zum Brute-Forcen', 'eine Webseite zum erstellen von Hashes', 'ein Fun-Projekt von LH', 'ein Hardware-Encoder'],
        'Was davon ist keine Linux-Distro?': ['Nexus', 'Gentoo', 'Ubuntu', 'Arch'],
        'Was davon ist nicht open source?': ['Google', 'Android', 'Linux', 'Visual Studio Code'],
        'Was davon ist am sichersten?': ['Signal', 'Telegram', 'WhatsApp', 'Discord'],
    }